name: CI

on:
  pull_request:
    branches: [main]
    

jobs:
  status_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
      
      - name: Install PortAudio dependencies
        run: sudo apt-get update && sudo apt-get install -y portaudio19-dev

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install ruff mypy pytest

      - name: Ruff
        run: ruff check .

      - name: Mypy
        run: mypy src && mypy tests

      - name: Pytest
        run: pytest